# Generated by Django 6.0.6 on 2026-08-06 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesssettings',
            name='linkedin_url',
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='design_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
