# Generated by Django 6.0.6 on 2026-06-24 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='design',
            name='preview_image',
        ),
        migrations.AddField(
            model_name='design',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='design',
            name='preview_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
