# Generated by Django 6.0.6 on 2026-06-25 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0002_remove_design_preview_image_design_is_submitted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='preview_image_url',
            field=models.URLField(blank=True, max_length=1100, null=True),
        ),
    ]
