# Generated by Django 6.0.6 on 2026-07-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0003_alter_design_preview_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='design',
            name='preview_image_url',
        ),
        migrations.AddField(
            model_name='design',
            name='back_preview_image_url',
            field=models.URLField(blank=True, max_length=1100, null=True),
        ),
        migrations.AddField(
            model_name='design',
            name='front_preview_image_url',
            field=models.URLField(blank=True, max_length=1100, null=True),
        ),
    ]
