# Generated by Django 6.0.6 on 2026-08-25 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0004_remove_design_preview_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='back_png_files',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='design',
            name='front_png_files',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
