# Generated by Django 6.0.6 on 2026-09-09 11:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0005_design_back_png_files_design_front_png_files'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='design',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='design',
            index=models.Index(fields=['user', '-created_at'], name='designs_user_id_5c5316_idx'),
        ),
    ]
