# Generated by Django 6.0.6 on 2026-07-26 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0002_feedback_admin_reply_feedback_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='admin_replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
