# Generated by Django 6.0.6 on 2026-07-27 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0003_feedback_admin_replied_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='quote_request',
        ),
    ]
