# Generated by Django 6.0.6 on 2026-07-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_cloudconnect_emailotp_alter_user_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudconnect',
            name='folder_ids',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
