# Generated by Django 6.0.6 on 2026-06-24 08:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallerydesign',
            name='image',
        ),
        migrations.AddField(
            model_name='gallerydesign',
            name='image_url',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gallerydesign',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gallerydesign',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='gallerydesign',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
