# Generated by Django 6.0.6 on 2026-06-25 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_remove_gallerydesign_image_gallerydesign_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerydesign',
            name='image_url',
            field=models.URLField(blank=True, max_length=1100, null=True),
        ),
    ]
