# Generated by Django 6.0.6 on 2026-07-28 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_gallerydesign_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallerydesign',
            name='image_url',
        ),
        migrations.AddField(
            model_name='gallerydesign',
            name='back_image_url',
            field=models.URLField(blank=True, max_length=1100, null=True),
        ),
        migrations.AddField(
            model_name='gallerydesign',
            name='front_image_url',
            field=models.URLField(blank=True, max_length=1100, null=True),
        ),
    ]
