# Generated by Django 6.0.6 on 2026-09-09 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_remove_gallerydesign_image_url_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='gallerydesign',
            index=models.Index(fields=['is_active', 'category'], name='gallery_des_is_acti_dd33fa_idx'),
        ),
    ]
