# Generated by Django 6.0.6 on 2026-06-29 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quoterequest',
            options={'ordering': ['-created_at']},
        ),
    ]
