# Generated by Django 6.0.6 on 2026-07-01 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0003_alter_design_preview_image_url'),
        ('gallery', '0003_alter_gallerydesign_image_url'),
        ('requests_app', '0002_alter_quoterequest_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='gallery_design',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='gallery.gallerydesign'),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='size_breakdown',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='design',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='designs.design'),
        ),
    ]
