# Generated by Django 6.0.6 on 2026-09-09 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0006_alter_design_options_and_more'),
        ('gallery', '0005_gallerydesign_gallery_des_is_acti_dd33fa_idx'),
        ('requests_app', '0003_quoterequest_gallery_design_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='quoterequest',
            index=models.Index(fields=['status', '-created_at'], name='quote_reque_status_369510_idx'),
        ),
        migrations.AddIndex(
            model_name='quoterequest',
            index=models.Index(fields=['email'], name='quote_reque_email_2a206b_idx'),
        ),
    ]
